
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 26 23:42:12 ICT 2015
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int WHILE = 7;
  public static final int NUMBER = 11;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int EQ = 5;
  public static final int ID = 12;
  public static final int error = 1;
  public static final int PRINT = 6;
  public static final int END = 10;
  public static final int BEGIN = 9;
  public static final int DO = 8;
}

