
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 28 06:14:21 ICT 2015
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int THEN = 11;
  public static final int SEMI = 2;
  public static final int WHILE = 13;
  public static final int END = 16;
  public static final int IF = 10;
  public static final int LPAREN = 7;
  public static final int ID = 18;
  public static final int DO = 14;
  public static final int BEGIN = 15;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int EQ = 9;
}

