
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 25 15:47:05 ICT 2015
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 6;
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int TIMES = 4;
  public static final int EOF = 0;
}

