
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 27 04:17:19 ICT 2015
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 6;
  public static final int EQ = 4;
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int NUMBER = 5;
  public static final int SEMI = 2;
  public static final int EOF = 0;
}

