
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 11 16:32:52 ICT 2015
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 3;
  public static final int EOF = 0;
}

